## <mark>Numpy</mark> :
 Numpy stands for numerical python. It is a python library used for fast numerical and mathematical operations on data.
 Numpy helps us work with large amounts of numbers efficiently using arrays.

### <mark>Why Numpy is used :</mark>
Normal python lists are slow for numerical computation. Numpy provides arrays that are :
- faster
- memory efficient
- designed for scientific computing and data science.

### <mark>Core concept : Numpy array<mark/>
A numpy array is similar to a python list but much more powerful.

example:

In [2]:
import numpy as np
arr = np.array([10,20,30,40])
print(arr)

[10 20 30 40]


- np → short name (alias) for NumPy,we can name whatever we want
- array() → a function that creates a NumPy array
- np.array() is a function used to convert a list or sequence into a NumPy array.

### <mark>Difference between List and NumPy array</mark>
Python List :

In [3]:
num = [1,2,3]


NumPy array :


In [4]:
num = np.array([1,2,3])

**but numpy array allows vector operations :**

In [5]:
arr = np.array([1,2,3])
print(arr*2)

[2 4 6]


**this is very powerful for data analysis**

### <mark>Types of NumPy array<mark/>

**-1D Array**

In [3]:
import numpy as np
arr = np.array([1,2,3,4])
print(arr)

[1 2 3 4]


**-2D Array (Rows and Columns)**

In [5]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


**-3D Array (Advanced)**

In [9]:
arr = np.array([
    [[1,2],[3,4]],
    [[5,6],[7,8]]
])
print(arr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### <mark>Important Arrays Properties:<mark/>

- 1. **array_name.shape:**

- It tells the number of rows and columns in a array.

In [6]:
import numpy as np
arr = np.array([[1,2,3,4],[4,5,6,7]])
print(arr.shape)

(2, 4)


 2. **array_name.size:**

- It tells the number of elements in the array.

In [8]:
print(arr.size)

8


**3. array_name.ndim:**

it tells the dimension of an array.

In [10]:
print(arr.ndim)

2


In [12]:
arr1 = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(arr1.ndim)

3


**4. array_name.dtype:**

It tells the data type inside the array.

In [13]:
print(arr.dtype)

int64


**Example:**

In [19]:
rohan = np.array([[[1,2,3,4],[4,5,6,7],[8,9,10,11]]])
print(rohan.shape)
print(rohan.size)
print(rohan.ndim)
print(rohan.dtype)

(1, 3, 4)
12
3
int64


### <mark>Creating array using Functions<mark/>

- **1. np.zeros() : is used to create an array filled with zeros of a specified shape.**

In [28]:
arr = np.zeros((2,3))
print(arr)
print(arr.ndim)


[[0. 0. 0.]
 [0. 0. 0.]]
2


for 3D arrays :

In [29]:
arr1 = np.zeros((2,2,3))
print(arr1)
print(arr1.ndim)

[[[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]]
3


Explanation of (2,2,3):

- 2 : number of 2D arrays (blocks)
- 2 : number of rows
- 3 : number of columns

**2. np.ones() : creates an array filled with ones of a specified shape**

In [30]:
arr = np.ones((2,3))
print(arr)

[[1. 1. 1.]
 [1. 1. 1.]]


**Note : np.zeros() and np.ones() use double parentheses because the first parentheses call the function and the second parentheses contain a tuple representing the shape of the array. Shape is provided in tuple**

**3. np.arange() : generates numbers in a specified range with a fixed step size. arange-array range**

In [31]:
arr = np.arange(1,10)
print(arr)

[1 2 3 4 5 6 7 8 9]


In [32]:
arr = np.arange(1,10,2)
print(arr)

[1 3 5 7 9]


(1,10,2)
- 1 : start value
- 10 : stop value(excluded)
- 2 : 