## <mark>Numpy</mark> :
 Numpy stands for numerical python. It is a python library used for fast numerical and mathematical operations on data.
 Numpy helps us work with large amounts of numbers efficiently using arrays.

### <mark>Why Numpy is used :</mark>
Normal python lists are slow for numerical computation. Numpy provides arrays that are :
- faster
- memory efficient
- designed for scientific computing and data science.

### <mark>Core concept : Numpy array<mark/>
A numpy array is similar to a python list but much more powerful.

example:

In [2]:
import numpy as np
arr = np.array([10,20,30,40])
print(arr)

[10 20 30 40]


- np → short name (alias) for NumPy,we can name whatever we want
- array() → a function that creates a NumPy array
- np.array() is a function used to convert a list or sequence into a NumPy array.

### <mark>Difference between List and NumPy array</mark>
Python List :

In [3]:
num = [1,2,3]


NumPy array :


In [4]:
num = np.array([1,2,3])

**but numpy array allows vector operations :**

In [5]:
arr = np.array([1,2,3])
print(arr*2)

[2 4 6]


**this is very powerful for data analysis**

### <mark>Types of NumPy array<mark/>

**-1D Array**

In [3]:
import numpy as np
arr = np.array([1,2,3,4])
print(arr)

[1 2 3 4]


**-2D Array (Rows and Columns)**

In [5]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


**-3D Array (Advanced)**

In [9]:
arr = np.array([
    [[1,2],[3,4]],
    [[5,6],[7,8]]
])
print(arr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### <mark>Important Arrays Properties:<mark/>

- 1. <mark>**array_name.shape: It tells the number of rows and columns in a array.**<mark/>

In [6]:
import numpy as np
arr = np.array([[1,2,3,4],[4,5,6,7]])
print(arr.shape)

(2, 4)


 2.<mark> **array_name.size: It tells the number of elements in the array.**<mark/>

In [8]:
print(arr.size)

8


**<mark>3. array_name.ndim: it tells the dimension of an array.**<mark/>

In [10]:
print(arr.ndim)

2


In [12]:
arr1 = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(arr1.ndim)

3


**4.<mark> array_name.dtype: It tells the data type inside the array.**<mark/>

In [13]:
print(arr.dtype)

int64


**Example:**

In [19]:
rohan = np.array([[[1,2,3,4],[4,5,6,7],[8,9,10,11]]])
print(rohan.shape)
print(rohan.size)
print(rohan.ndim)
print(rohan.dtype)

(1, 3, 4)
12
3
int64


### <mark>Creating array using Functions<mark/>

- **1. <mark>np.zeros()<mark/> : is used to create an array filled with zeros of a specified shape.**

In [28]:
arr = np.zeros((2,3))
print(arr)
print(arr.ndim)


[[0. 0. 0.]
 [0. 0. 0.]]
2


for 3D arrays :

In [29]:
arr1 = np.zeros((2,2,3))
print(arr1)
print(arr1.ndim)

[[[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]]
3


Explanation of (2,2,3):

- 2 : number of 2D arrays (blocks)
- 2 : number of rows
- 3 : number of columns

**2.<mark> np.ones()<mark/>: creates an array filled with ones of a specified shape**

In [30]:
arr = np.ones((2,3))
print(arr)

[[1. 1. 1.]
 [1. 1. 1.]]


**Note : np.zeros() and np.ones() use double parentheses because the first parentheses call the function and the second parentheses contain a tuple representing the shape of the array. Shape is provided in tuple**

**3.<mark> np.arange()<mark/> : generates numbers in a specified range with a fixed step size. arange-array range**

In [31]:
arr = np.arange(1,10)
print(arr)

[1 2 3 4 5 6 7 8 9]


In [32]:
arr = np.arange(1,10,2)
print(arr)

[1 3 5 7 9]


(1,10,2)
- 1 : start value
- 10 : stop value(excluded)
- 2 : step size

4. <mark>**np.linspce(): Creates evenly spaced numbers between start and end**<mark/>

In [2]:
import numpy as np
arr = np.linspace(0,10,5)
print(arr)

[ 0.   2.5  5.   7.5 10. ]


- 0 → Start value, the sequence begins from 0
- 10 → End value (included) ,the sequence ends at 10
- 5 → Number of values

In [3]:
arr = np.linspace(4,5,8)
print(arr)

[4.         4.14285714 4.28571429 4.42857143 4.57142857 4.71428571
 4.85714286 5.        ]


- arange() → you give step size
- linspace() → you give number of values

5. <mark>**np.eye(n) : It  creates an identity elements. n is no. of rows = no,. of columnns(square matrix)**<mark/>

In [4]:
arr = np.eye(3)
print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [6]:
arr = np.eye(1)
print(arr)

[[1.]]


### <mark>Random generation Function<mark/>

 <mark>**6. np.random.rand(R,C) : generates an array of random numbers between 0 and 1.<mark/>**

In [8]:
arr = np.random.rand(2,3)
arr

array([[0.9547017 , 0.42148877, 0.24985006],
       [0.61795568, 0.70396654, 0.9697248 ]])

**<mark>7. np.random.randn(R,C) : Generates random numbers from normal distribution (mean=0, std=1) . Values of array ranges from -3 to +3<mark/>**


In [9]:
import numpy as np
arr = np.random.randn(2,3)
print(arr)

[[ 3.09988389  0.37883409 -1.36717969]
 [ 0.42443316 -0.69185618 -1.08020926]]


<mark>**8.np.random.randint(Start,End,size=(R,c)) : generates random integer for array**<mark/>

In [10]:
arr = np.random.randint(1,100,size=(2,3))
arr

array([[35, 15, 53],
       [ 9, 77, 60]], dtype=int32)

### **<mark>NUMPY INDEXING AND SLICING OF VECTORS<mark/>**

In NumPy, vectors are just 1D arrays, and indexing/slicing is how you access or extract elements from them.

In [11]:
import numpy as np

In [12]:
arr = np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

#### **<mark>Positive Indexing<mark/>**

In [15]:
print(arr[0])
print(arr[2])
print(arr[8])

1
3
9


#### <mark>**Negative Indexing<mark/>**

In [17]:
print(arr[-1])
print(arr[-2])
print(arr[-15])

30
29
16


#### <mark>**Slicing (Access Multiple Elements)**<mark/>

**Syntax:**

```arr[start : end : step]```

In [21]:
print(arr[0:8]) #it will go index 0 to 7

[1 2 3 4 5 6 7 8]


In [24]:
print(arr[0:8:2]) #it will print every second value

[1 3 5 7]


In [26]:
print(arr[:7]) # default value of start is 0

[1 2 3 4 5 6 7]


In [28]:
print(arr[5:]) # default value of end is the last index + 1

[ 6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29
 30]


In [30]:
print(arr[:]) # it will print the vector

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30]


In [32]:
print(arr[::2]) # step = 2 (skip one element)

[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29]


In [33]:
print(arr[::-1]) # it will reverse the vector

[30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7
  6  5  4  3  2  1]


#### <mark> **View vs copy**<mark/>

**Slicing creates a view not a copy , changes affect the original array.**

In [34]:
arr1 = np.arange(0,6)
print(arr1)



[0 1 2 3 4 5]


In [35]:
slice_arr = arr1[0:3]
print(slice_arr)

[0 1 2]


In [38]:
slice_arr[1]=10
print(arr1)

[ 0 10  2  3  4  5]


**to avoid this problem use copy**

In [40]:
slice_arr = arr1[0:3].copy()
slice_arr[1] = 100
print(slice_arr)
print(arr1)

[  0 100   2]
[ 0 10  2  3  4  5]


#### <mark>**Fancy Indexing : Access multiple specific indices**<mark/>

In [41]:
arr2 = np.arange(10,31)
print(arr2)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30]


In [42]:
print(arr2[[0,3,5]])

[10 13 15]


### <mark>**NUMPY INDEXING AND SLICING OF MATRIX**<mark/>

In NumPy, a matrix is a 2D array, so indexing and slicing involve rows and columns.


In [43]:
import numpy as np
arr3 = np.arange(1,31).reshape(6,5)
print(arr3)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]


#### <mark>**INDEXING IN MATRIX**<maark/>

**Syntax:**

``` arr[row,column]```

In [45]:
print(arr3[0,0])
print(arr3[3,4])

1
20


**Negative Indexing**

In [46]:
print(arr3[-1,-1])
print(arr3[-2,-5])

30
21


#### **<mark>SELECTING ENTRE ROW / COLUMN<mark/>**

In [50]:
print(arr3[3]) # it will give row of index 3

[16 17 18 19 20]


OR

In [52]:
print(arr3[3, :])

[16 17 18 19 20]


In [55]:
print(arr3[:,3]) # it will give column of index 3

[ 4  9 14 19 24 29]


#### **<mark>SLICING ROWS AND COLUMNS<mark/>**

**Syntax:**


```arr[row_start:row_end , col_start:col_end]```

In [58]:
print(arr3[0:2,1:3]) # it will start from row of index 0 and moves to row of index 2-1=1 same for column


[[2 3]
 [7 8]]


In [62]:
print(arr3[3:,3: ]) # it will start for row of index 0 and moves until last because we dont provvide end value same as for column

[[19 20]
 [24 25]
 [29 30]]


In [66]:
print(arr3[:2,:]) # it will give first two rows because for selecting two rows you have select all columns so you dont give any index for column default values will do its job

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [68]:
print(arr3[:,:2]) # it will give first two column same logic as before

[[ 1  2]
 [ 6  7]
 [11 12]
 [16 17]
 [21 22]
 [26 27]]


#### <mark>**STEP SLICING<mark/>**

In [72]:
arr3

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [73]:
print(arr3[::2,::2])

[[ 1  3  5]
 [16 18 20]]


Rows → ::2
- Take row 0
- Skip row 1
- Take row 2

Columns → ::2
- Take col 0
- Skip col 1
- Take col 2

In [74]:
print(arr3[1::2,1:3])

[[ 7  8]
 [17 18]
 [27 28]]


#### <mark>**BOOLEAN INDEXING**<mark/>

**In NumPy, boolean indexing is a powerful way to filter data using conditions . It means selecting elements using True / False conditions.**

In [75]:
arr3

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [76]:
print(arr3>15)

[[False False False False False]
 [False False False False False]
 [False False False False False]
 [ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]]


In [77]:
print(arr3[arr3>15])

[16 17 18 19 20 21 22 23 24 25 26 27 28 29 30]


**<mark>NOTE:<mark/>**

**First,it checks the condition on a matrix and gives a boolean maatrix as output then feed this as index in the original matrix name to fetch the values
and output will be 1D array**

In [84]:
print(arr3[arr3<10]) # it will give the values less than 10 from the matrix arrr3

[1 2 3 4 5 6 7 8 9]


In [79]:
print(arr3[arr3%2==0])

[ 2  4  6  8 10 12 14 16 18 20 22 24 26 28 30]


In [83]:
print(arr3[(arr3>5) & (arr3<15)])

[ 6  7  8  9 10 11 12 13 14]


#### <mark>**Modify values using Boolean Indexing**<mark/>

In [88]:
arr3[arr3>25]=0 # it will modify those values which is greater than 25 and change to 0 . It is very useful in Data cleaning
print(arr3) 

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [ 0  0  0  0  0]]


In [90]:
arr3[(arr3>5) & (arr3<10)] = 1
print(arr3)

[[ 1  2  3  4  5]
 [ 1  1  1  1 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [ 0  0  0  0  0]]


<mark>**NOTE : BOOLEAN INDEXING is also works in vector <mark/>**

#### <mark>**NumPy OPERATIONS**<mark/>

**Operations = doing math on arrays . Instead of loops, NumPy does it fast and directly**

In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3])
b = np.array([4,5,6])

In [4]:
print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a//b) # it wll give floor value
print(a**b)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[0 0 0]
[  1  32 729]


<mark>**This is called element-wise operation**<mark/>

#### <mark>**OPERATION WITH SCALAR**<mark/>

In [6]:
print(a+10)
print(b-5)

[11 12 13]
[-1  0  1]


#### <mark>**Matrix Multiplication**<mark/>

In [8]:
a = np.arange(1,21).reshape(5,4)
b = np.arange(21,41).reshape(5,4)
print(a)
print(b)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]
[[21 22 23 24]
 [25 26 27 28]
 [29 30 31 32]
 [33 34 35 36]
 [37 38 39 40]]


In [9]:
print(a+b)
print(a-b)
print(a*b) # this is not matrix multiplication , this is element wise multiplication
print(a/b)

[[22 24 26 28]
 [30 32 34 36]
 [38 40 42 44]
 [46 48 50 52]
 [54 56 58 60]]
[[-20 -20 -20 -20]
 [-20 -20 -20 -20]
 [-20 -20 -20 -20]
 [-20 -20 -20 -20]
 [-20 -20 -20 -20]]
[[ 21  44  69  96]
 [125 156 189 224]
 [261 300 341 384]
 [429 476 525 576]
 [629 684 741 800]]
[[0.04761905 0.09090909 0.13043478 0.16666667]
 [0.2        0.23076923 0.25925926 0.28571429]
 [0.31034483 0.33333333 0.35483871 0.375     ]
 [0.39393939 0.41176471 0.42857143 0.44444444]
 [0.45945946 0.47368421 0.48717949 0.5       ]]


##### <mark>**MATRIX MULTIPLICATION**<mark/>

In [15]:
a = np.arange(1,17).reshape(4,4)
b = np.arange(18,34).reshape(4,4)
print(a)
print(b)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[[18 19 20 21]
 [22 23 24 25]
 [26 27 28 29]
 [30 31 32 33]]


In [16]:
c = np.dot(a,b)
c

array([[ 260,  270,  280,  290],
       [ 644,  670,  696,  722],
       [1028, 1070, 1112, 1154],
       [1412, 1470, 1528, 1586]])

**OR**

In [17]:
c = a@b
c

array([[ 260,  270,  280,  290],
       [ 644,  670,  696,  722],
       [1028, 1070, 1112, 1154],
       [1412, 1470, 1528, 1586]])

##### <mark>**TRANSPOSE OF A MATRIX**<mark/>

In [18]:
print(a.T)

[[ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]
 [ 4  8 12 16]]


In [19]:
print(b.T)

[[18 22 26 30]
 [19 23 27 31]
 [20 24 28 32]
 [21 25 29 33]]


**Rows become columns**

#### <mark>**USEFUL MAATHEMATICAL OPERATION**<mark/>

In [20]:
a = np.array([1,4,9,16,25])
print(np.sqrt(a))

[1. 2. 3. 4. 5.]


In [21]:
print(np.exp(a))

[2.71828183e+00 5.45981500e+01 8.10308393e+03 8.88611052e+06
 7.20048993e+10]


In [22]:
print(np.log(a))

[0.         1.38629436 2.19722458 2.77258872 3.21887582]


#### <mark>**AGGEREGATION OPERATION**<mark/>

In [23]:
a = np.arange(1,11)
print(a)

[ 1  2  3  4  5  6  7  8  9 10]


In [25]:
print(np.sum(a))

55


In [26]:
print(np.mean(a))

5.5


In [27]:
print(np.max(a))

10


In [28]:
print(np.min(a))

1


#### <mark>**MATRIX AGGREGATION**<mark/>

In [29]:
b = np.arange(1,21).reshape(5,4)
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [30]:
print(np.sum(b,axis=0)) # columnwise sum

[45 50 55 60]


In [31]:
print(np.sum(b,axis=1)) #rowise sum

[10 26 42 58 74]


### <mark>**BROADCASTING**<mark/>

**NumPy automatically makes arrays the same shape to perform operations . So you don’t need loops.**

In [32]:
arr = np.array([1, 2, 3])
print(arr + 5)

[6 7 8]


NumPy internally does: 
``` [1 2 3] ```
``` [5 5 5] ```  ← expanded automatically

In [33]:
a = np.array([1, 2, 3])
b = np.array([10])
print(a + b)

[11 12 13]


b is stretched to match a

In [34]:
arr = np.array([
    [1, 2],
    [3, 4]
])

print(arr + 10)

[[11 12]
 [13 14]]


10 added to every element

In [35]:
arr = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

b = np.array([10, 20, 30])

print(arr + b)

[[11 22 33]
 [14 25 36]]


What happened:
Matrix:
[[1 2 3]
 [4 5 6]]

Vector:
[10 20 30]

Becomes:
[[10 20 30]
 [10 20 30]]

#### <mark>**SPLITTING OF ARRAY**<mark/>